### PR TITLE
Jyee/datadog monitoring

### PR DESCRIPTION
**Pull request by jyee**
Adds datadog yaml files.

### CODE REVIEW

**Comment by jyee** [comment]
@nibalizer Also take a look at https://github.com/DataDog/istio101/tree/master/workshop/exercise-4

**Comment by nibalizer** [comment]
:toot: :hammer: :science: :microscope: :tada: :+1:

**Comment by nibalizer** [comment]
@svennam92 can you review as well? It'll be a hot minute before I have time to go through this

**Comment by svennam92** [comment]
LGTM

**Review by nibalizer — APPROVED** [review]

**Pull request merged**
